#cargo-features = ["edition2024"]
[package]
name = "backend"
version = "0.1.0"
edition = "2024"
authors = ["Dominic Clifton <me@dominicclifton.name>"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
crux_core = { workspace = true }
project = { workspace = true }