#cargo-features = ["edition2024"]
[package]
name = "signals_slots"
version = "0.1.0"
edition = "2024"

[dependencies]
mobius_egui = { workspace = true }

[[bin]]
name = "signals_slots"
path = "src/main.rs"