#cargo-features = ["edition2024"]
[package]
name = "signals_slots"
version = "0.2.0"
edition = "2024"

[dependencies]
egui_mobius = { workspace = true }

[[bin]]
name = "signals_slots"
path = "src/main.rs"