#cargo-features = ["edition2024"]
[package]
name = "simple_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
mobius_egui = { workspace = true }
egui = { workspace = true }
eframe = { workspace = true, default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
] }
rand = { workspace = true }

[[bin]]
name = "simple_monitor"
path = "src/main.rs"