[package]
name = "simple_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.0"
egui = "0.31.0"
mobius_egui = { path = "../../mobius_egui" }
rand = "0.9.0"
tokio = {version = "1.43.0", features = ["full"]}
winit = "0.30.9"
crossbeam-channel = "0.5.14"
