[package]
name = "frontend"
version = "0.1.0"
edition = "2024"
authors = ["Dominic Clifton <me@dominicclifton.name>"]

[dependencies]
backend = { workspace = true }
egui_mobius = { workspace = true }

egui = { workspace = true }
eframe = { workspace = true, default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
] }
rand = { workspace = true }
tokio = { workspace = true, features = ["full"]}
winit = { workspace = true }
crossbeam-channel = { workspace = true }

env_logger = { workspace = true }
log = { workspace = true }

[[bin]]
name = "egui_crux_example"
path = "src/main.rs"